<?xml version="1.0"?>
<package format="3">
  <name>warehouse_gazebo</name>
  <version>0.0.1</version>
  <description>Gazebo world, models and spawn launch for warehouse sim</description>
  <maintainer email="you@email.com">Dong</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>